config/routes.rb
MoviesApp::Application.routes.draw do

  get '/movies', controller: 'movies', action: 'index', as: 'movies'

  get '/movies/new', controller: 'movies', action: 'new', as: 'new_movie'

  get '/movies/:id', controller: 'movies', action: 'show', as: 'movie'

  get '/movies/:id/edit', controller: 'movies', action: 'edit', as: 'edit_movie'
  put '/movies/:id', controller: 'movies', action: 'update'

  post '/movies', controller: 'movies', action: 'create'

  delete '/movies/:id', controller: 'movies', action: 'destroy'


  get '/theaters', controller: 'theaters', action: 'index', as: 'theaters'

  get '/theaters/new', controller: 'theaters', action: 'new', as: 'new_theater'

  get '/theaters/:id', controller: 'theaters', action: 'show', as: 'theater'

  get '/theaters/:id/edit', controller: 'theaters', action: 'edit', as: 'edit_theater'
  put '/theaters/:id', controller: 'theaters', action: 'update'

  post '/theaters', controller: 'theaters', action: 'create'

  delete '/theaters/:id', controller: 'theaters', action: 'destroy'


end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/models/theater.rb
class Theater < ActiveRecord::Base

  # This model should have the following attributes:
  # Attribute Name   |  Attribute Type
  # ----------------------------------
  # name             |  String
  # address          |  String
  # phone_number     |  String

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find_by_id(params[:id])
  end

  def new

  end

  def create
    m = Movie.new
    m.title = params[:title]
    m.year = params[:year]
    m.save

    redirect_to movies_url
  end

  def edit
    @movie = Movie.find_by_id(params[:id])
  end

  def update
    @movie = Movie.find_by_id(params[:id])
    @movie.title = params[:title]
    @movie.year = params[:year]
    @movie.save
    redirect_to movies_url
  end

  def destroy
    m = Movie.find_by_id(params[:id])
    m.destroy
    redirect_to movies_url
  end





end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController

  def index
    @theaters = Theater.all
  end

  def show
    @theater = Theater.find_by_id(params[:id])
  end

  def new
  end

  def create
    m = Theater.new
    m.name = params[:name]
    m.address = params[:address]
    m.phone = params[:phone]
    m.save

    redirect_to theaters_url
  end

  def edit
    @theater = Theater.find_by_id(params[:id])
  end

  def update
    @theater = Theater.find_by_id(params[:id])
    @theater.name = params[:name]
    @theater.address = params[:address]
    @theater.phone = params[:phone]
    @theater.save

    redirect_to theaters_url
  end

  def destroy
    theater = Theater.find_by_id(params[:id])
    theater.destroy
    redirect_to theaters_url
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoviesApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/edit.html.erb
<h1>Editing Movie #<%= @movie.id %></h1>

<%= form_tag(movie_url(@movie.id), :method => :put) do %>
  <p><%= label_tag :title %>
    <%= text_field_tag :title, @movie.title %></p>


  <p><%= label_tag :year %>
    <%= text_field_tag :year, @movie.year %></p>

  <p><%= submit_tag %></p>
<% end %>

app/views/movies/index.html.erb
<h1>Movie Database</h1>

<%= image_tag 'rails.png' %>
<p><%= link_to "Add a New Movie", new_movie_path %></p>
<!-- <p><a href="/movies/new">Add a New Movie</a></p> -->

<table>
  <thead>
    <tr>
      <th>ID Number</th>
      <th>Title</th>
     <!--  <th>Director</th> -->
      <th>Year</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.id, movie %></td>
        <td><%= movie.title %></td>
        <td><%= movie.year %></td>
        <td>
          <%= link_to "Edit", edit_movie_path(movie) %>
          <%= link_to "Delete", movie, :method => :delete %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= form_tag(movies_url) do %>
  <p><%= label_tag :title %>
    <%= text_field_tag :title %></p>


  <p><%= label_tag :year %>
    <%= text_field_tag :year %></p>

  <p><%= submit_tag %></p>
<% end %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>

<hr>
<p>Year: <%= @movie.year %></p>

app/views/theaters/edit.html.erb
<h1>Editing Theater #<%= @theater.id %></h1>

<%= form_tag(theater_url(@theater.id), :method => :put) do %>
  <p><%= label_tag :name %>
    <%= text_field_tag :name, @theater.name %></p>


  <p><%= label_tag :address %>
    <%= text_field_tag :address, @theater.address %></p>



  <p><%= label_tag :phone %>
    <%= text_field_tag :phone, @theater.phone %></p>


  <p><%= submit_tag %></p>
<% end %>

app/views/theaters/index.html.erb
<h1>Theater Database</h1>

<%= image_tag 'rails.png' %>
<p><%= link_to "Add a New Theater", new_theater_url %></p>
<!-- <p><a href="/movies/new">Add a New Movie</a></p> -->

<table>
  <thead>
    <tr>
      <th>ID Number</th>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @theaters.each do |theater| %>
      <tr>
        <td><%= link_to theater.id, theater %></td>
        <td><%= theater.name %></td>
        <td><%= theater.address %></td>
        <td><%= theater.phone %></td>
        <td>
          <%= link_to "Edit", edit_theater_path(theater) %>
          <%= link_to "Delete", theater, :method => :delete %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/theaters/new.html.erb
<h1>New Theater</h1>

<%= form_tag(theaters_url) do %>
  <p><%= label_tag :name %>
    <%= text_field_tag :name %></p>


  <p><%= label_tag :address %>
    <%= text_field_tag :address %></p>

  <p><%= label_tag :phone %>
    <%= text_field_tag :phone %></p>

  <p><%= submit_tag %></p>
<% end %>

app/views/theaters/show.html.erb
<h1><%= @theater.name %></h1>

<hr>
<p>Phone: <%= @theater.phone %></p>